### ISSUE TITLE
未能连接到vpnagent服务，请重新安装本软件

### ISSUE THREAD

**Issue by fcwys** [tlslink/anylink-client#19]
一直提示这个，重新安装也不行：
![image](https://github.com/tlslink/anylink-client/assets/28641034/c7956a33-b3ae-45b9-ace7-f85c2113e6bb)

**Comment by itviewer** [comment]
重启电脑，或者下0.8.1试试

**Comment by fcwys** [comment]
换到0.8.1可以了，请问下这个是什么原因呢？

**Comment by itviewer** [comment]
不太确定，最近比较忙，回头抽空研究下

**Comment by fcwys** [comment]
连接思科的出现这个，请问下这个是啥问题呢？
![image](https://github.com/tlslink/anylink-client/assets/28641034/9089b9d2-9fc2-4e6c-890e-3ace8cdf0271)

**Comment by itviewer** [comment]
首页加 客户端的  qq 群

**Comment by fcwys** [comment]
好的
