### ISSUE TITLE
希望增加 macos 客户端

### ISSUE THREAD

**Issue by awklinux** [tlslink/anylink-client#20]
希望增加 macos 客户端，公司有很多同事希望能用上 macos 版本的客户端，谢谢。

**Comment by itviewer** [comment]
看看有没有大气的朋友有**闲置**的mac笔记本可以借用一两周吧，短期内我自己没有购入mac设备的计划，没场景，买了也是吃灰

**Comment by itviewer** [comment]
macos 目前已经可以使用，[安装说明](https://github.com/tlslink/anylink-client?tab=readme-ov-file#macos)
我自己目前使用会出现断线重连问题，不确定是我自己服务器问题还是客户端软件问题，有兴趣的话可以帮忙测试一下。
使用一段时间后看下 关于-查看连接日志
