### ISSUE TITLE
退出重连报错Error starting session: The system cannot find the file 

### ISSUE THREAD

**Issue by blfish008** [tlslink/anylink-client#22]
退出重连极大概率会出现报错，多连几次又能连上了
Error starting session: The system cannot find the file specified。

**Comment by itviewer** [comment]
开启调试，重连，让它重现错误，然后去日志里复制全贴到这里

**Comment by blfish008** [comment]
X-Cstp-Tcp-Keepalive: false
X-Cstp-Tunnel-All-Dns: false
X-Cstp-Version: 1
X-Dtls-Dpd: 10
X-Dtls-Keepalive: 4
X-Dtls-Mtu: 1399
X-Dtls-Port: 443
X-Dtls-Rekey-Method: new-tunnel
X-Dtls-Rekey-Time: 43200
X-Dtls-Session-Id: 86ce5f76cda1ff741a55c5cacf92f9e46d9f8b156dc66ba51ce42ae83a7be866
X-Dtls12-Ciphersuite: ECDHE-ECDSA-AES128-GCM-SHA256

2023/10/08 14:12:29 tun.go:20: [Error] failed to creates a new tun interface
2023/10/08 14:12:29 rpc.go:120: [Error] Error starting session: The system cannot find the file specified.

**Comment by itviewer** [comment]
这个可能和特定系统有关，我这不能重现问题，换台电脑试试吧
