### ISSUE TITLE
Setting not saved when using non-admin account in Windows

### ISSUE THREAD

**Issue by papiru5** [tlslink/anylink-client#26]
Hi, today I test AnyLink Secure Client v.0.8.8 at work with non-admin account and saw, that when I turn option in settings "Connect to the last used VPN..." on, after application restart It became unchecked again. I test it on several computers with the same result.
![изображение](https://github.com/tlslink/anylink-client/assets/147839328/07a24e94-76ac-4aa7-8ebb-3dbfd7a1052c)
With admin account it behave as expected. Can you check it, please?

**Comment by itviewer** [comment]
It's a bug.
for now,you can keep unconnected status, change config then exit, it should save the config.

**Comment by papiru5** [comment]
Thank you for workaround, tested it on several computers, It works fine.
