### ISSUE TITLE
希望能增加同时连接多个 vpn 功能

### ISSUE THREAD

**Issue by awklinux** [tlslink/anylink-client#27]
目前公司有两个机房，经常需要连接两个地方，现在只能断开一个连接另外一个，希望能增加个功能，能同时连接两个或者多个

**Comment by itviewer** [comment]
软件本身无法实现。如却有需要，可以自己尝试研究修改，或者我单独定制编译一份（有偿），相当于另一个软件，比如叫anylink client2，只有这种办法
